// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PnuColumns holds the columns for the "pnu" table.
	PnuColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "jibun", Type: field.TypeString},
		{Name: "bchk", Type: field.TypeString},
		{Name: "pnu", Type: field.TypeString},
		{Name: "col_adm_se", Type: field.TypeString},
		{Name: "geometry", Type: field.TypeOther, SchemaType: map[string]string{"mysql": "GEOMETRY", "postgres": "geometry"}},
	}
	// PnuTable holds the schema information for the "pnu" table.
	PnuTable = &schema.Table{
		Name:       "pnu",
		Columns:    PnuColumns,
		PrimaryKey: []*schema.Column{PnuColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PnuTable,
	}
)

func init() {
	PnuTable.Annotation = &entsql.Annotation{
		Table: "pnu",
	}
}
